# -*- coding: utf-8 -*-
"""K-Means.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q2DsDuyrnkRCw-b-p4e8TDX3ByVIskGW
"""

from google.colab import files
uploaded=files.upload()

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import silhouette_score

df=pd.read_csv('Mall_Customers.csv')
df

X=df[["Annual Income (k$)","Spending Score (1-100)"]]

scaler=StandardScaler()
X_scaled=scaler.fit_transform(X)

inertia_list=[]

for k in range(1, 11):
    km=KMeans(n_clusters=k,random_state=42)
    km.fit(X_scaled)
    inertia_list.append(km.inertia_)

plt.plot(range(1, 11), inertia_list, marker="o")
plt.xlabel("Number of Clusters (K)")
plt.ylabel("Inertia")
plt.title("Elbow Method for Optimal K")
plt.show()

k=5
kmeans=KMeans(n_clusters=k, random_state=42)
labels=kmeans.fit_predict(X_scaled)

df["Cluster"]=labels

score=silhouette_score(X_scaled,labels)
print("Silhouette Score:",score)

plt.scatter(X_scaled[:, 0],X_scaled[:, 1],c=labels,s=60)
plt.xlabel("Annual Income (Scaled)")
plt.ylabel("Spending Score (Scaled)")
plt.title("Customer Segments (K-Means Clustering)")
plt.show()

